### ISSUE TITLE
Mirror Microsoft/ChakraCore into chakra-core/ChakraCore

### ISSUE THREAD

**Issue by ppenzin** [chakra-core/org#6]
I am trying to set it up as an automated mirror, in hope we can setting up CI for it. @chakra-core/core , what do you think about it?

P.S. I disabled branch protection for `master`, but I do remember how to turn it back on :)

**Comment by ppenzin** [comment]
As discussed in #8, I am trying to set up the automated mirror in preparations for our release. I'll keep an eye on commits coming from the Microsoft repo to make sure it works. I still need to play with it a little, for example "mirror" clone has access to original releases (including files), but that would disable posting build artefacts from the mirror.

**Comment by rhuanjl** [comment]
I think this has served its purpose.

**Comment by ppenzin** [comment]
I went ahead and deleted the clone, I don't think we need it anymore.
